apiVersion: v1
kind: Service
metadata:
  name: servicio
  labels:
    app: temp-deploy
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30005
      protocol: TCP
  selector:
    app: temp-deploy
